---
- name: WordPress on Nginx (no FastCGI caching), PHP-FPM, MariaDB

  hosts: webservers
  remote_user: root
  vars:
    wp_hhvm: true
    hhvm_start: true

  roles:
    - reset-all-configs
    - hhvm
    - nginx

