---
- name: >
    WordPress on Nginx (no FastCGI caching), PHP-FPM, MariaDB
    Includes WP-CLI

  hosts: webservers
  remote_user: root

  roles:
    - common
    - php
    - wp-cli
    - mariadb
    - wordpress-install
    - php-fpm
    - nginx
