---
- name: WordPress with WooCommerce, Jetpack and dummy data

  hosts: webservers
  remote_user: deploy
  vars:
    wp_advanced: true
    wp_dummy_data: true

  roles:
    - reset-wordpress
    - wordpress-install

